#!/bin/bash
# Instructions pour lancer Gazebo + LIMO + apprentissage

URDF_PATH="\$(xacro \$(ros2 pkg prefix limo_description)/share/limo_description/urdf/limo_four_diff.xacro)"

echo ""
echo "======================================================"
echo "  LANCEMENT GAZEBO + LIMO — 4 terminaux à ouvrir"
echo "======================================================"
echo ""
echo "--- Terminal 1 : Gazebo ---"
echo "  ros2 launch gazebo_ros gazebo.launch.py"
echo ""
echo "  Attendre que Gazebo soit complètement démarré, puis ouvrir le Terminal 2."
echo ""
echo "--- Terminal 2 : robot_state_publisher ---"
echo "  ros2 run robot_state_publisher robot_state_publisher \\"
echo "    --ros-args -p robot_description:=\"$URDF_PATH\""
echo ""
echo "--- Terminal 3 : spawn du robot ---"
echo "  ros2 run gazebo_ros spawn_entity.py -entity limo -topic robot_description"
echo ""
echo "  Attendre que le robot apparaisse dans Gazebo, puis ouvrir le Terminal 4."
echo ""
echo "--- Terminal 4 : apprentissage ---"
echo "  cd ~/Bureau/torch_ros"
echo "  source ~/Bureau/venvRobot/bin/activate"
echo "  python3 ros2_torch_run.py"
echo ""
echo "======================================================"
echo ""
